# Site settings
title: Cahaba Pressure
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Cahaba Pressure Treated Forest Products
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.cahabahapressure.com" # the base hostname & protocol for your site

# Build settings
gems: [bourbon,'modular-scale']
markdown: kramdown
